import { useEffect, useMemo, useState } from 'react'
import { Activity, AlertTriangle, Check, ChevronRight, FolderOpen, Gauge, Play, Plus, RefreshCw, Settings, UploadCloud, X } from 'lucide-react'
import UploadButton from './UploadButton'
import { API, api, csrf } from './upload'

type Job = { id:string; filename:string; status:string; stage:string; progress:number; priority:number; mode:Record<string, string | boolean | number | null>; error?:string; warnings?:string[]; created_at?:string }
type Segment = { id:number; ordinal:number; start_ms:number; end_ms:number; source_text:string; translated_text:string; reading_text:string; tempo?:number; warnings:string[]; revision:number }
type Artifact = { id:string; kind:string; path:string; size_bytes?:number; valid:boolean }
function formatStatus(status:string) { return ({QUEUED:'Đang chờ',RUNNING:'Đang xử lý',PAUSING:'Đang tạm dừng',CANCELLING:'Đang hủy',PAUSED:'Tạm dừng',COMPLETED:'Hoàn tất',COMPLETED_WITH_WARNINGS:'Hoàn tất có cảnh báo',FAILED:'Lỗi',CANCELLED:'Đã hủy',SKIPPED_NO_AUDIO:'Không có audio',SKIPPED_NO_SPEECH:'Không có lời nói'} as Record<string,string>)[status] || status }
function formatStage(stage:string) { return ({preflight:'Kiểm tra',audio:'Tách audio',asr:'Whisper',translation:'Dịch NLLB',tts:'Piper',render:'Ghép video',verify:'Kiểm tra kết quả'} as Record<string,string>)[stage] || stage }

export default function App() {
  const [jobs,setJobs] = useState<Job[]>([]); const [selected,setSelected] = useState<Job|null>(null); const [segments,setSegments] = useState<Segment[]>([]); const [artifacts,setArtifacts] = useState<Artifact[]>([]); const [dirty,setDirty] = useState(false); const [view,setView] = useState<'queue'|'settings'>('queue'); const [busy,setBusy] = useState(false); const [message,setMessage] = useState(''); const [uploadMessage,setUploadMessage] = useState('')
  const refresh = async () => { try { const data = await api('/jobs'); setJobs(data); setSelected(previous => previous ? data.find((j:Job)=>j.id===previous.id) || null : null) } catch(e) { setMessage((e as Error).message) } }
  useEffect(() => { refresh(); const timer=setInterval(refresh,3000); const events=new EventSource(API+'/events'); events.onmessage=refresh; events.addEventListener('progress',refresh); events.addEventListener('completed',refresh); events.addEventListener('failed',refresh); return()=>{clearInterval(timer);events.close()} }, [])
  useEffect(() => { if (!selected || dirty) return; const timer=setInterval(()=>{api(`/jobs/${selected.id}/segments`).then(setSegments).catch(()=>{});api(`/jobs/${selected.id}/artifacts`).then(setArtifacts).catch(()=>{})},3000); return()=>clearInterval(timer) }, [selected?.id,dirty])
  const counts = useMemo(() => ({active:jobs.filter(j=>['QUEUED','RUNNING','PAUSED'].includes(j.status)).length, done:jobs.filter(j=>j.status.startsWith('COMPLETED')).length, failed:jobs.filter(j=>j.status==='FAILED').length}), [jobs])
  const selectJob = async (job:Job) => { setSelected(job); setDirty(false); const [rows,files]=await Promise.all([api(`/jobs/${job.id}/segments`),api(`/jobs/${job.id}/artifacts`)]); setSegments(rows);setArtifacts(files) }
  const action = async (job:Job, name:string) => { setBusy(true); try { await api(`/jobs/${job.id}/${name}`, {method:'POST',headers:{'X-CSRF-Token':csrf()}}); await refresh() } catch(e) { setMessage((e as Error).message) } finally { setBusy(false) } }
  const changePriority = async (job:Job, priority:number) => { setBusy(true); try { await api(`/jobs/${job.id}/priority`, {method:'PATCH',headers:{'X-CSRF-Token':csrf()},body:JSON.stringify({priority})}); await refresh() } catch(e) { setMessage((e as Error).message) } finally { setBusy(false) } }
  const saveSegments = async () => { if (!selected) return; setBusy(true); try { const draft=await api(`/jobs/${selected.id}/draft`,{method:'POST',headers:{'X-CSRF-Token':csrf()}}); const draftSegments:Segment[]=await api(`/jobs/${draft.id}/segments`); const updates=draftSegments.map(ds=>{const edited=segments.find(s=>s.ordinal===ds.ordinal); return {id:ds.id,translated_text:edited?.translated_text ?? ds.translated_text,reading_text:edited?.reading_text ?? ds.reading_text,revision:ds.revision}}); await api(`/jobs/${draft.id}/segments`,{method:'PATCH',headers:{'X-CSRF-Token':csrf()},body:JSON.stringify(updates)}); await api(`/jobs/${draft.id}/render`,{method:'POST',headers:{'X-CSRF-Token':csrf()}}); setDirty(false); setMessage('Đã lưu bản dịch và tạo phiên bản xuất mới') } catch(e) { setMessage((e as Error).message) } finally { setBusy(false) } }
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark">VA</div><div><strong>Video Auto</strong><span>Local studio</span></div></div>
      <nav><button className={view==='queue'?'active':''} onClick={()=>setView('queue')}><Activity size={18}/> Hàng đợi</button><button className={view==='settings'?'active':''} onClick={()=>setView('settings')}><Settings size={18}/> Cài đặt</button></nav>
      <div className="sidebar-foot"><div className="local-dot"/><span>Đang chạy local</span></div>
    </aside>
    <main className="main"><header><div><p className="eyebrow">WORKSPACE CÁ NHÂN</p><h1>{view==='queue'?'Dịch & lồng tiếng video':'Cài đặt hệ thống'}</h1></div><UploadButton visible={view==='queue'} onShowQueue={()=>setView('queue')} onDone={refresh} onError={setUploadMessage} onClearError={()=>setUploadMessage('')}/></header>
      {(uploadMessage || message)&&<div className="toast"><AlertTriangle size={16}/>{uploadMessage || message}<button onClick={()=>uploadMessage ? setUploadMessage('') : setMessage('')}><X size={15}/></button></div>}
      {view==='queue'?<><section className="metrics"><Metric icon={<Activity/>} label="Đang xử lý" value={counts.active}/><Metric icon={<Check/>} label="Đã hoàn tất" value={counts.done}/><Metric icon={<AlertTriangle/>} label="Cần kiểm tra" value={counts.failed}/><Metric icon={<Gauge/>} label="Chế độ" value="CPU local" text/></section><section className="content-grid"><div className="panel queue-panel"><div className="panel-head"><div><h2>Hàng đợi xử lý</h2><p>Video mới sẽ tự chạy theo preset hiện tại.</p></div><button className="icon-btn" onClick={refresh}><RefreshCw size={17}/></button></div>{jobs.length===0?<Empty onDone={refresh}/>:<div className="job-list">{jobs.map(job=><JobRow key={job.id} job={job} selected={selected?.id===job.id} onClick={()=>selectJob(job)} onAction={action} onPriority={changePriority} busy={busy}/>)}</div>}</div><Detail job={selected} segments={segments} setSegments={setSegments} markDirty={()=>setDirty(true)} artifacts={artifacts} save={saveSegments} /></section></>:<><SettingsView onMessage={setMessage}/><WatchFolders onMessage={setMessage}/></>} 
    </main>
  </div>
}
function Metric({icon,label,value,text=false}:{icon:React.ReactNode;label:string;value:number|string;text?:boolean}) { return <div className="metric"><div className="metric-icon">{icon}</div><div><span>{label}</span><strong className={text?'small-value':''}>{value}</strong></div></div> }
function JobRow({job,selected,onClick,onAction,onPriority,busy}:{job:Job;selected:boolean;onClick:()=>void;onAction:(j:Job,a:string)=>void;onPriority:(j:Job,p:number)=>void;busy:boolean}) {
  const actionName=job.status==='PAUSED'?'resume':job.status==='FAILED'?'retry':job.status==='QUEUED'?'pause':job.status==='RUNNING'?'pause':null
  const canPrioritize=['QUEUED','RETRY_WAIT','WAITING_RESOURCES','PAUSED'].includes(job.status)
  const priorityValue = Number.isFinite(job.priority) ? job.priority : 0
  const standardPriority = [10, 0, -10].includes(priorityValue)
  return <div className={`job-row ${selected?'selected':''}`} onClick={onClick}><div className="file-icon"><Play size={16}/></div><div className="job-main"><div className="job-title">{job.filename}</div><div className="job-meta">{formatStage(job.stage)} <span>·</span> {new Date(job.created_at||'').toLocaleString('vi-VN')}</div><div className="progress"><i style={{width:`${job.progress}%`}}/></div></div>{canPrioritize&&<label className="priority-control" onClick={event=>event.stopPropagation()}>Ưu tiên<select aria-label={`Ưu tiên ${job.filename}`} disabled={busy} value={priorityValue} onChange={event=>onPriority(job,Number(event.target.value))}>{!standardPriority&&<option value={priorityValue}>Tùy chỉnh ({priorityValue})</option>}<option value={10}>Cao</option><option value={0}>Bình thường</option><option value={-10}>Thấp</option></select></label>}{actionName&&<button className="row-action" disabled={busy} onClick={event=>{event.stopPropagation();onAction(job,actionName)}}>{actionName==='resume'?'Tiếp tục':actionName==='retry'?'Thử lại':'Tạm dừng'}</button>}<div className={`status ${job.status.toLowerCase()}`}>{job.status==='RUNNING'&&<span className="pulse"/>}{formatStatus(job.status)}</div><ChevronRight size={17} className="chevron"/></div>
}
function Detail({job,segments,setSegments,markDirty,artifacts,save}:{job:Job|null;segments:Segment[];setSegments:(s:Segment[])=>void;markDirty:()=>void;artifacts:Artifact[];save:()=>void}) { if(!job)return <div className="panel detail empty-detail"><div className="empty-art"><FolderOpen size={25}/></div><h2>Chọn một video</h2><p>Xem tiến độ, transcript và chỉnh bản dịch tại đây.</p></div>; const terminal=job.status==='SKIPPED_NO_AUDIO'?'Video này không có audio để xử lý.':job.status==='SKIPPED_NO_SPEECH'?'Không phát hiện lời nói trong audio.': 'Nội dung transcript sẽ xuất hiện sau khi Whisper hoàn tất.'; return <div className="panel detail"><div className="panel-head"><div><p className="eyebrow">CHI TIẾT VIDEO</p><h2>{job.filename}</h2></div><div className={`status ${job.status.toLowerCase()}`}>{formatStatus(job.status)}</div></div><div className="stage-line"><div className="stage-active" style={{width:`${job.progress}%`}}/><span>{formatStage(job.stage)} · {Math.round(job.progress)}%</span></div>{job.error&&<div className="error-box"><AlertTriangle size={16}/>{job.error}</div>}<div className="mode-pills"><span>{job.mode.audio_mode==='mix'?'Trộn audio gốc':'Thay audio gốc'}</span><span>{job.mode.subtitle_mode==='burn'?'Phụ đề ghi vào hình':job.mode.subtitle_mode==='soft'?'Phụ đề bật/tắt':job.mode.subtitle_mode==='srt'?'SRT rời':'Không phụ đề'}</span>{job.mode.include_original_track===true&&<span>Giữ track audio gốc phụ</span>}</div><div className="segments">{segments.length?segments.map((s,i)=><div className="segment" key={s.id}><time>{(s.start_ms/1000).toFixed(1)}s</time><div><p>{s.source_text}</p><textarea value={s.translated_text} onFocus={markDirty} onChange={e=>{markDirty();setSegments(segments.map(x=>x.id===s.id?{...x,translated_text:e.target.value,reading_text:e.target.value}:x))}}/>{s.warnings.length>0&&<small className="warning">{s.warnings.join(' · ')}</small>}</div></div>):<p className="muted">{terminal}</p>}</div>{artifacts.length>0&&<div className="artifact-list">{artifacts.map(a=><a key={a.id} href={`${API}/artifacts/${a.id}`} target="_blank" rel="noreferrer"><DownloadIcon kind={a.kind}/>{a.kind} · {a.path}</a>)}</div>}{segments.length>0&&<button className="primary save" onClick={save}>Lưu bản dịch & xuất lại <ChevronRight size={16}/></button>}</div> }
function DownloadIcon({kind}:{kind:string}) { return kind==='video'?<Play size={13}/>:<FolderOpen size={13}/> }
function Empty({onDone}:{onDone:()=>void}) { return <div className="empty"><div className="empty-art"><UploadCloud size={28}/></div><h3>Chưa có video trong hàng đợi</h3><p>Tải video local lên để bắt đầu dịch và lồng tiếng.</p><button className="secondary" onClick={onDone}><RefreshCw size={15}/> Làm mới</button></div> }
function SettingsView({onMessage}:{onMessage:(x:string)=>void}) { const [data,setData]=useState<Record<string,any>|null>(null); const [saving,setSaving]=useState(false); useEffect(()=>{api('/settings').then(setData).catch(e=>onMessage(e.message))},[]); if(!data)return <div className="panel empty"><p>Đang tải cài đặt…</p></div>; const save=async()=>{setSaving(true);try{const result=await api('/settings',{method:'PATCH',headers:{'X-CSRF-Token':csrf()},body:JSON.stringify({max_file_bytes:Number(data.max_file_bytes),max_duration_seconds:Number(data.max_duration_seconds),stable_seconds:Number(data.stable_seconds),cpu_threads:Number(data.cpu_threads)})});setData(result);onMessage('Đã lưu cài đặt')}catch(e){onMessage((e as Error).message)}finally{setSaving(false)}};return <section className="settings-grid"><div className="panel settings-card"><p className="eyebrow">GIỚI HẠN</p><h2>Hàng đợi & tài nguyên</h2><label>Giới hạn dung lượng (bytes)<input type="number" value={data.max_file_bytes} onChange={e=>setData({...data,max_file_bytes:e.target.value})}/></label><label>Thời lượng tối đa (giây)<input type="number" value={data.max_duration_seconds} onChange={e=>setData({...data,max_duration_seconds:e.target.value})}/></label><label>Số luồng CPU<input type="number" min="1" max="64" value={data.cpu_threads} onChange={e=>setData({...data,cpu_threads:e.target.value})}/></label><button className="primary save" onClick={save} disabled={saving}>{saving?'Đang lưu…':'Lưu thay đổi'}</button></div><div className="panel settings-card"><p className="eyebrow">LOCAL RUNTIME</p><h2>Mô hình & công cụ</h2>{['whisper_model','nllb_model','piper_model','ffmpeg','ffprobe'].map(key=><div className="path-row" key={key}><span>{key}</span><code>{data[key]||'Chưa cấu hình'}</code></div>)}<div className="offline"><span className="local-dot"/> Offline mode bật · không gửi dữ liệu ra ngoài</div></div></section> }
function WatchFolders({onMessage}:{onMessage:(x:string)=>void}) { const [rows,setRows]=useState<any[]>([]); const [path,setPath]=useState(''); const load=()=>api('/watch-folders').then(setRows).catch(e=>onMessage(e.message)); useEffect(()=>{load()},[]); const add=async()=>{if(!path.trim())return;try{await api('/watch-folders',{method:'POST',headers:{'X-CSRF-Token':csrf()},body:JSON.stringify({path:path.trim(),preset:{audio_mode:'replace',subtitle_mode:'burn',include_dubbing:true}})});setPath('');load()}catch(e){onMessage((e as Error).message)}}; const remove=async(id:string)=>{try{await api(`/watch-folders/${id}`,{method:'DELETE',headers:{'X-CSRF-Token':csrf()}});load()}catch(e){onMessage((e as Error).message)}}; return <div className="panel watch-card"><p className="eyebrow">TỰ ĐỘNG HÓA</p><h2>Thư mục theo dõi</h2><p>Video được giữ ổn định 30 giây rồi tự đưa vào hàng đợi.</p><div className="watch-add"><input value={path} onChange={e=>setPath(e.target.value)} placeholder="C:\\Videos\\Inbox"/><button className="secondary" onClick={add}><Plus size={15}/> Thêm</button></div>{rows.map(row=><div className="watch-row" key={row.id}><FolderOpen size={15}/><code>{row.path}</code><button className="icon-btn" onClick={()=>remove(row.id)}><X size={14}/></button></div>)}</div> }
